openapi: 3.0.0
info:
  version: '1.2.2'
  title: 'Common Data Types'
  description: |
    Common Data Types for Service Based Interfaces.
    © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.571 Common Data Types for Service Based Interfaces, version 16.6.0
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.571/'

paths: {}
components:
  schemas:
    # TS29510_Nnrf_NFManagement
    NFProfile:
      description: Information of an NF Instance registered in the NRF
      type: object
      required:
        - nfInstanceId
        - nfType
        - nfStatus
      anyOf: # FIXME: Not handled
        - required: [ fqdn ]
        - required: [ ipv4Addresses ]
        - required: [ ipv6Addresses ]
      properties:
        nfInstanceId:
          type: string
          description: for TEST string
        nfType:
          type: string
          description: for TEST string
        nfStatus:
          type: string
          description: for TEST string
        fqdn:
          type: string
          description: for TEST string
        ipv4Addresses:
          type: string
          description: for TEST string
        ipv6Addresses:
          type: string
          description: for TEST string
