openapi: 3.0.0
info:
  version: '1.2.2'
  title: 'Common Data Types'
  description: |
    Common Data Types for Service Based Interfaces.
    © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.571 Common Data Types for Service Based Interfaces, version 16.6.0
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.571/'

paths: {}
components:
  schemas:
    PcfBindingPatch:
      type: object
      properties:
        ipv4Addr:
          $ref: '#/components/schemas/Ipv4AddrRm'
        ipv6Addr:
          $ref: '#/components/schemas/Ipv6Addr'
    Ipv4AddrRm:
      type: string
      pattern: '^(([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$'
      example: '198.51.100.1'
      nullable: true
    Ipv6Addr:
      type: string
      # FIXME: not generated because of allOf pattern
      allOf:
        - pattern: '^((:|(0?|([1-9a-f][0-9a-f]{0,3}))):)((0?|([1-9a-f][0-9a-f]{0,3})):){0,6}(:|(0?|([1-9a-f][0-9a-f]{0,3})))$'
        - pattern: '^((([^:]+:){7}([^:]+))|((([^:]+:)*[^:]+)?::(([^:]+:)*[^:]+)?))$'
      example: '2001:db8:85a3::8a2e:370:7334'
