openapi: 3.0.0
info:
  version: '1.2.2'
  title: 'Common Data Types'
  description: |
    Common Data Types for Service Based Interfaces.
    © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.

externalDocs:
  description: 3GPP TS 29.571 Common Data Types for Service Based Interfaces, version 16.6.0
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.571/'

paths: {}
components:
  schemas:
    # TS29571_CommonData.yaml
    Uri:
      type: string
    InvalidParam:
      type: object
      properties:
        param:
          type: string
        reason:
          type: string
      required:
        - param
    SupportedFeatures:
      type: string
      pattern: '^[A-Fa-f0-9]*$'
    ProblemDetails:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/Uri'
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          $ref: '#/components/schemas/Uri'
        cause:
          type: string
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/InvalidParam'
          minItems: 1
        supportedFeatures:
          $ref: '#/components/schemas/SupportedFeatures'
        targetScp:
          $ref: '#/components/schemas/Uri'

    # TS29502_Nsmf_PDUSession.yaml
    ExtProblemDetails:
      allOf:
      - $ref: '#/components/schemas/ProblemDetails'
      - $ref: '#/components/schemas/ProblemDetailsAddInfo'
    ProblemDetailsAddInfo:
      type: object
      properties:
        remoteError:
          type: boolean

    # TS29510_Nnrf_NFManagement
    SubscriptionData:
      description: Information of a subscription to notifications to NRF events, included in subscription requests and responses
      type: object
      properties:
        requesterFeatures:
          writeOnly: true
          allOf:
            - $ref: '#/components/schemas/SupportedFeatures'
        nrfSupportedFeatures:
          readOnly: true
          allOf:
            - $ref: '#/components/schemas/SupportedFeatures'

    # TS29522_TrafficInfluence.yaml
    TrafficInfluSub:
      type: object
      properties:
        afAppId:
          type: string
          description: Identifies an application.
        trafficFilters:
          type: string
          description: for TEST string
        ipv4Addr:
          type: string
          description: for TEST string
        ipv6Addr:
          type: string
          description: for TEST string
        subscribedEvents:
          type: string
          description: for TEST string
        notificationDestination:
          type: string
          description: for TEST string
      allOf:
        - oneOf:
          - required: [afAppId]
          - required: [trafficFilters]
        - oneOf:
          - required: [ipv4Addr]
          - required: [ipv6Addr]
      # FIXME: not support anyOf
      anyOf:
        - not:
            required: [subscribedEvents]
        - required: [notificationDestination]
