openapi: 3.0.0
info:
  title: Npcf_SMPolicyControl API
  version: 1.1.3
  description: |
    Session Management Policy Control Service
    © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
externalDocs:
  description: 3GPP TS 29.512 V16.7.0; 5G System; Session Management Policy Control Service.
  url: 'http://www.3gpp.org/ftp/Specs/archive/29_series/29.512/'

paths: {}
components:
  schemas:
    SmPolicyDecision:
      type: object
      properties:
        sessRules:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/SessionRule'
          minProperties: 1
          description: A map of Sessionrules with the content being the SessionRule as described in subclause 5.6.2.7.
        pccRules: # FIXME: nullable, but Not generated nullable object
          type: object
          additionalProperties:
            $ref: '#/components/schemas/PccRule'
          minProperties: 1
          description: A map of PCC rules with the content being the PCCRule as described in subclause 5.6.2.6.
          nullable: true
    SessionRule:
      type: object
      properties:
        sessRuleId:
          type: string
          description: Univocally identifies the session rule within a PDU session.
    PccRule:
      type: object
      properties:
        appId:
          type: string
          description: A reference to the application detection filter configured at the UPF.
