openapi: 3.0.0
info:
  title: Nchf_ConvergedCharging
  version: 3.0.1
  description: |
    ConvergedCharging Service    © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
    All rights reserved.
externalDocs:
  description: >
    3GPP TS 32.291 V16.6.0: Telecommunication management; Charging management; 
    5G system, charging service; Stage 3.
  url: 'http://www.3gpp.org/ftp/Specs/archive/32_series/32.291/'

paths: {}
components:
  schemas:
    # FIXME: Not Generated, Why?
    EnhancedDiagnostics5G:
      $ref: '#/components/schemas/RanNasCauseList'

    # need options : --additional-properties=generateAliasAsModel=true
    ranNasRelCauses:
      type: array
      items:
        $ref: '#/components/schemas/RanNasRelCause'
      minItems: 1

    # need options : --additional-properties=generateAliasAsModel=true
    RanNasCauseList:
      type: array
      items:
        $ref: '#/components/schemas/RanNasRelCause'

    RanNasRelCause:
      type: object
      properties:
        ngApCause:
          type: string
        5gMmCause:
          type: string
        5gSmCause:
          type: string
        epsCause:
          type: string
